# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Copy package.json and package-lock.json (if available)
COPY package.json ./

# Install dependencies
RUN npm install --ignore-scripts

# Copy the rest of the application source code
COPY . .

# Build the application
RUN npm run build

# Expose any port if necessary (usually MCP communication is via stdio, so not needed)

# Set the default command to run the MCP server
CMD [ "npm", "start" ]
